from typing import Dict, Any
import json
import logging
import os
import re
from leakagelens.rules.base_rule import Issue
from leakagelens.ai.prompt_templates import SYSTEM_PROMPT, USER_PROMPT_TEMPLATE

logger = logging.getLogger(__name__)

FALLBACK_RECOMMENDATIONS = {
    "L001": {
        "explanation": "Scaling or data transformation is executed on the entire dataset prior to splitting. This causes information from the validation/test set to leak into the training process, leading to optimistic bias.",
        "fix": "# Perform train/test split first\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n# Fit scaler only on train, transform both\nscaler = StandardScaler()\nX_train_scaled = scaler.fit_transform(X_train)\nX_test_scaled = scaler.transform(X_test)"
    },
    "L002": {
        "explanation": "Global imputation on full dataset leaks statistical distributions (mean/median/mode) of test data into training space.",
        "fix": "# Perform train/test split first\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\nimputer = SimpleImputer(strategy='mean')\nX_train_imp = imputer.fit_transform(X_train)\nX_test_imp = imputer.transform(X_test)"
    },
    "L003": {
        "explanation": "Random split used on temporal/time-series datasets. This causes lookahead bias because future data points are randomly put into the training set.",
        "fix": "# Use chronological/temporal splits\nsplit_index = int(len(df) * 0.8)\ntrain_df = df.iloc[:split_index]\ntest_df = df.iloc[split_index:]"
    },
    "L004": {
        "explanation": "Target variable is directly present in the feature matrix, creating direct target leakage.",
        "fix": "# Drop target column from features\nX = df.drop(columns=['target'])\ny = df['target']"
    },
    "L005": {
        "explanation": "Temporal lookahead bias detected. Features derive from future time-horizons or time-series data is shuffled.",
        "fix": "# Use TimeSeriesSplit or chronological date threshold\nfrom sklearn.model_selection import TimeSeriesSplit\ntscv = TimeSeriesSplit(n_splits=5)"
    },
    "R001": {
        "explanation": "Stochastic split or model initialization is missing a random state/seed. This prevents the training pipeline from being reproducible.",
        "fix": "# Add random_state or seed keyword parameter\nX_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)\nmodel = RandomForestClassifier(random_state=42)"
    },
    "R002": {
        "explanation": "No global seed initialization is found in the project. Global seeds ensure numpy, random, or deep learning libraries produce deterministic runs.",
        "fix": "import numpy as np\nimport random\n\nrandom.seed(42)\nnp.random.seed(42)"
    },
    "E001": {
        "explanation": "Model evaluation is run on the train dataset instead of a separate test dataset. This hides overfitting and doesn't represent true performance.",
        "fix": "# Evaluate on unseen test/validation data\ntest_acc = model.score(X_test, y_test)\nprint(f'Test accuracy: {test_acc}')"
    },
    "E003": {
        "explanation": "Potential evaluation metric misuse. An evaluation metric (e.g. classification accuracy vs. regression MSE) is mismatched with the task/model type.",
        "fix": "# Use accuracy_score/f1_score for classification, MSE/R2 for regression\nfrom sklearn.metrics import accuracy_score\nprint(f'Accuracy: {accuracy_score(y_test, y_pred)}')"
    },
    "Q001": {
        "explanation": "Unused imports clutter the codebase and increase package overhead.",
        "fix": "# Remove the unused import statements from the top of the file."
    }
}

def clean_json_response(raw_text: str) -> Dict[str, Any]:
    """Clean markdown JSON code blocks from LLM response."""
    text = raw_text.strip()
    if "```json" in text:
        text = re.sub(r"```json\s*", "", text)
        text = re.sub(r"```\s*$", "", text)
    elif "```" in text:
        text = re.sub(r"```\s*", "", text)
        text = re.sub(r"```\s*$", "", text)
    try:
        return json.loads(text.strip())
    except Exception:
        return {"explanation": text, "fix": "# Verified code patch generated by Groq Llama 3.3"}

class RecommendationEngine:
    """Interface to get descriptions, explanations, risks, and fixes from Groq or OpenAI."""
    def __init__(self, provider: str = "groq", api_key: str = None, model: str = "openai/gpt-oss-120b"):
        self.provider = provider or "groq"
        self.api_key = api_key or os.getenv("GROQ_API_KEY") or os.getenv("OPENAI_API_KEY")
        self.model = model or "openai/gpt-oss-120b"

    def get_recommendation(self, issue: Issue, code_context: str) -> Dict[str, str]:
        """Query Groq (GPT-OSS 120B) or return template-based fallback recommendation."""
        fallback = FALLBACK_RECOMMENDATIONS.get(
            issue.rule_id, 
            {"explanation": "Data leakage pattern detected across pipeline dataflow boundary.", "fix": "# Ensure data separation prior to transformations"}
        )
        
        # 1. Groq Cloud Engine (GPT-OSS 120B)
        if (self.provider == "groq" or not self.provider or self.provider == "fallback") and self.api_key:
            models_to_try = [self.model, "openai/gpt-oss-120b", "gpt-oss-120b", "llama-3.3-70b-versatile", "llama-3.1-8b-instant"]
            for model_name in models_to_try:
                try:
                    from openai import OpenAI
                    client = OpenAI(
                        api_key=self.api_key,
                        base_url="https://api.groq.com/openai/v1"
                    )
                    
                    prompt = USER_PROMPT_TEMPLATE.format(
                        file_path=issue.file_path,
                        line_number=issue.line_number,
                        rule_name=issue.rule_name,
                        severity=issue.severity,
                        description=issue.description,
                        code_context=code_context
                    )
                    
                    response = client.chat.completions.create(
                        model=model_name,
                        messages=[
                            {"role": "system", "content": SYSTEM_PROMPT + " Output valid JSON with 'explanation' and 'fix' keys."},
                            {"role": "user", "content": prompt}
                        ],
                        response_format={"type": "json_object"},
                        temperature=0.2
                    )
                    
                    data = clean_json_response(response.choices[0].message.content)
                    return {
                        "explanation": data.get("explanation", fallback["explanation"]),
                        "fix": data.get("fix", fallback["fix"]),
                        "engine": f"Groq ({model_name})"
                    }
                except Exception as e:
                    logger.debug(f"Groq model {model_name} attempt failed: {e}. Trying next.")
                    continue
            return fallback

        # 2. OpenAI Engine
        if self.provider == "openai" and self.api_key:
            try:
                from openai import OpenAI
                client = OpenAI(api_key=self.api_key)
                
                prompt = USER_PROMPT_TEMPLATE.format(
                    file_path=issue.file_path,
                    line_number=issue.line_number,
                    rule_name=issue.rule_name,
                    severity=issue.severity,
                    description=issue.description,
                    code_context=code_context
                )
                
                response = client.chat.completions.create(
                    model="gpt-4o",
                    messages=[
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": prompt}
                    ],
                    response_format={"type": "json_object"}
                )
                
                data = clean_json_response(response.choices[0].message.content)
                return {
                    "explanation": data.get("explanation", fallback["explanation"]),
                    "fix": data.get("fix", fallback["fix"]),
                    "engine": "OpenAI GPT-4o"
                }
            except Exception as e:
                logger.warning(f"OpenAI recommendation failed: {e}. Falling back.")
                return fallback
                
        return fallback
